version: '3.8'

services:
  parser:
    build: ./parser
    depends_on:
      - rabbitmq
    volumes:
      - ./parser:/app
    command: python main.py -c 1 2 3

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - '5432:5432'

  faststream_service:
    build: ./faststream_service
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./faststream_service:/app
    command: python main.py
